project:
  type: book
  output-dir: docs

book:
  title: "Mandat analyse de données de ventes Dunin"
  author: "Datcha Beugre"
  date: today
  repo-url: https://github.com/datchaa/dunin_etl
  repo-actions: [source]
  sidebar:
    style: docked

  chapters:
    - index.qmd
    - part: "Phase 1 : collecte de données"
      chapters:
        - scripts/data_collection.qmd
        - scripts/data_cleaning.qmd
        - scripts/data_loading.qmd
        - scripts/data_exploratory.qmd
    - part: "Phase 2 : Implémentation de l'architecture ETL (Microsoft SSIS)"
      chapters: []
   
format:
  html:
    theme: 
      - cosmo
      - brand
    css: styles.css
    toc: true

page-footer:
  left: "© 2025 Datcha Beugre"

publish:
  method: gh-pages
